export const IPC_CHANNELS = {
  APP_GET_VERSION: 'app:getVersion',
  APP_GET_PLATFORM: 'app:getPlatform',
  DIALOG_SELECT_VIDEO_FILE: 'dialog:selectVideoFile',
  DIALOG_SELECT_SUBTITLE_FILE: 'dialog:selectSubtitleFile',
  DIALOG_SELECT_OUTPUT_DIRECTORY: 'dialog:selectOutputDirectory',
  SYSTEM_GET_CAPABILITIES: 'system:getCapabilities',
  FFMPEG_CHECK_AVAILABILITY: 'ffmpeg:checkAvailability',
  DATABASE_GET_HEALTH: 'database:getHealth',
  PROJECT_CREATE: 'project:create',
  PROJECT_LIST: 'project:list',
  PROJECT_GET: 'project:get',
  PROJECT_DELETE: 'project:delete',
  PROJECT_INSPECT: 'project:inspect',
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_SELECT_FFMPEG_PATH: 'settings:selectFfmpegPath',
  SETTINGS_SELECT_FFPROBE_PATH: 'settings:selectFfprobePath',
  QUEUE_LIST: 'queue:list',
  QUEUE_CREATE_DEMO_JOB: 'queue:createDemoJob',
  SUBTITLE_SELECT_FOR_PROJECT: 'subtitle:selectForProject',
  SUBTITLE_PARSE_FOR_PROJECT: 'subtitle:parseForProject',
  SUBTITLE_CLEAR_FOR_PROJECT: 'subtitle:clearForProject',
  SYNC_CHECK_FOR_PROJECT: 'sync:checkForProject',
  VIDEO_GET_PLAYBACK_URL: 'video:getPlaybackUrl',
  VIDEO_GET_CUES: 'video:getCues',
  TRANSCRIPT_GENERATE_FOR_PROJECT: 'transcript:generateForProject',
  TRANSCRIPT_EXPORT_FOR_PROJECT: 'transcript:exportForProject',
  AI_GET_CONFIGURATION_STATUS: 'ai:getConfigurationStatus',
  AI_SET_API_KEY: 'ai:setApiKey',
  AI_TEST_CONNECTION: 'ai:testConnection',
  AI_CANCEL_TEST: 'ai:cancelTest',
  AI_CLEAR_CONFIGURATION: 'ai:clearConfiguration',
  AI_RECORD_CONSENT: 'ai:recordConsent',
  AI_GENERATE_CANDIDATES: 'ai:generateCandidates',
  AI_CANCEL_GENERATION: 'ai:cancelGeneration',
  AI_LIST_CANDIDATES: 'ai:listCandidates',
  AI_UPDATE_CANDIDATE_STATUS: 'ai:updateCandidateStatus',
} as const;

export const ALL_IPC_CHANNELS = Object.values(IPC_CHANNELS);
